//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matrix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Matrix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This client is not registered as a application service client. You can&apos;t create new appservice users..
        /// </summary>
        internal static string AppserviceNotRegistered {
            get {
                return ResourceManager.GetString("AppserviceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while trying to connect..
        /// </summary>
        internal static string ConnnectionException {
            get {
                return ResourceManager.GetString("ConnnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is not valid..
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing body in message..
        /// </summary>
        internal static string MessageBodyMissing {
            get {
                return ResourceManager.GetString("MessageBodyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing MessageType in message,.
        /// </summary>
        internal static string MessageTypeMissing {
            get {
                return ResourceManager.GetString("MessageTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t convert obj to JSON..
        /// </summary>
        internal static string ObjToJsonFail {
            get {
                return ResourceManager.GetString("ObjToJsonFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An OnMessage handler failed..
        /// </summary>
        internal static string OnMessageFail {
            get {
                return ResourceManager.GetString("OnMessageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not decode sync..
        /// </summary>
        internal static string SyncDecodeFail {
            get {
                return ResourceManager.GetString("SyncDecodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [warn] A Matrix exception occured during sync!.
        /// </summary>
        internal static string SyncMatrixException {
            get {
                return ResourceManager.GetString("SyncMatrixException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start thread, already running..
        /// </summary>
        internal static string ThreadAlreadyRunning {
            get {
                return ResourceManager.GetString("ThreadAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the user&apos;s membership event..
        /// </summary>
        internal static string UserMembershipEventNotFound {
            get {
                return ResourceManager.GetString("UserMembershipEventNotFound", resourceCulture);
            }
        }
    }
}
